// Generated by CoffeeScript 1.12.4
(function() {
  var compile, eco, precompile, preprocess, ref;

  ref = require("./compiler"), compile = ref.compile, precompile = ref.precompile;

  preprocess = require("./preprocessor").preprocess;

  module.exports = eco = function(source) {
    var base;
    if (eco.cache) {
      return (base = eco.cache)[source] != null ? base[source] : base[source] = compile(source);
    } else {
      return compile(source);
    }
  };

  eco.cache = {};

  eco.preprocess = preprocess;

  eco.precompile = precompile;

  eco.compile = compile;

  eco.render = function(source, data) {
    return (eco(source))(data);
  };

  if (require.extensions) {
    require.extensions[".eco"] = function(module, filename) {
      var source;
      source = require("fs").readFileSync(filename, "utf-8");
      return module._compile("module.exports = " + (precompile(source)), filename);
    };
  }

}).call(this);
